import { Section } from '../classes/section';

export const dropdown = [
  new Section({
    id: 'nav-11',
    title: 'Dropdown Dark',
    type: 'dropdown',
    styles: {
      nav: {
        display: 'flex',
        'justify-content': 'space-between',
        'align-items': 'center',
        color: 'white',
        'background-color': 'rgb(0, 0, 0)',
        height: '10vh',
        margin: '1em 0',
      },
      logo: {
        'font-size': '24px',
        'letter-spacing': '2px',
        'padding-left': '1.5em',
      },
      list: {
        display: 'flex',
        'justify-content': 'space-around',
        height: '100%',
        padding: '0 1em',
      },
      item: {
        display: 'flex',
        'align-items': 'center',
        padding: '0 1.5rem',
        transition: 'background-color 200ms',
      },
      link: {
        'flex-direction': 'column',
        'align-items': 'center',
        'justify-content': 'center',
        display: 'flex',
        padding: '0 .5em',
        'font-size': '16px',
        'text-decoration': 'none',
        color: 'white',
        cursor: 'pointer',
      },
      hover: {
        'background-color': 'gray',
      },
      dropdown: {
        item: {
          display: 'flex',
          position: 'relative',
        },
        icon: {
          'margin-left': ' 0.5rem',
          'font-weight': 'bold',
          transition: 'transform 300ms',
        },
        content: {
          display: 'none',
          'flex-direction': 'column',
          position: 'absolute',
          left: 0,
          top: '10vh',
          width: '100%',
          padding: 0,
          height: 'max-content',
          'background-color': 'black',
          animation: 'slide 300ms ease',
        },
      },
      keyframes: {
        name: 'silde',
        from: {
          opacity: 0,
          transform: 'translateY(-60px)',
        },
        to: {
          opacity: 1,
          transform: 'translateY(0)',
        },
      },
    },
    items: ['Home', 'Contacts', 'About'],
    dropdown: {
      title: 'Dropdown',
      items: ['Media', 'Downloads'],
    },
  }),
  new Section({
    id: 'nav-12',
    title: 'Dropdown Light',
    type: 'dropdown',
    styles: {
      nav: {
        display: 'flex',
        'justify-content': 'space-between',
        'align-items': 'center',
        color: 'black',
        'background-color': 'rgb(255,255,255)',
        height: '10vh',
        margin: '1em 0',
      },
      logo: {
        'font-size': '24px',
        'letter-spacing': '2px',
        'padding-left': '1.5em',
      },
      list: {
        display: 'flex',
        'justify-content': 'space-around',
        padding: '0 1em',
        height: '100%',
      },
      item: {
        display: 'flex',
        transition: 'background-color 200ms',
        'align-items': 'center',
        padding: '0 1.5rem',
      },
      link: {
        'flex-direction': 'column',
        'align-items': 'center',
        'justify-content': 'center',
        display: 'flex',
        padding: '0 .5em',
        'font-size': '16px',
        'text-decoration': 'none',
        color: 'black',
      },
      hover: {
        'background-color': 'lightgray',
      },
      dropdown: {
        item: {
          display: 'flex',
          position: 'relative',
        },
        icon: {
          'margin-left': ' 0.5rem',
          'font-weight': 'bold',
          transition: 'transform 300ms',
        },
        content: {
          display: 'none',
          'flex-direction': 'column',
          position: 'absolute',
          left: 0,
          top: '10vh',
          width: '100%',
          padding: 0,
          height: 'max-content',
          'background-color': 'white',
          animation: 'slide 300ms ease',
        },
      },
      keyframes: {
        name: 'silde',
        from: {
          opacity: 0,
          transform: 'translateY(-60px)',
        },
        to: {
          opacity: 1,
          transform: 'translateY(0)',
        },
      },
    },
    items: ['Home', 'Contacts', 'About'],
    dropdown: {
      title: 'Dropdown',
      items: ['Media', 'Downloads'],
    },
  }),
  new Section({
    id: 'nav-13',
    title: 'Dropdown Blue',
    type: 'dropdown',
    styles: {
      nav: {
        display: 'flex',
        'justify-content': 'space-between',
        'align-items': 'center',
        color: 'white',
        'background-color': '#2B34FF',
        height: '10vh',
        margin: '1em 0',
      },
      logo: {
        'font-size': '24px',
        'letter-spacing': '2px',
        'padding-left': '1.5em',
      },
      list: {
        display: 'flex',
        'justify-content': 'space-around',
        padding: '0 1em',
        height: '100%',
      },
      item: {
        display: 'flex',
        transition: 'background-color 200ms',
        'align-items': 'center',
        padding: '0 1.5rem',
      },
      link: {
        'flex-direction': 'column',
        'align-items': 'center',
        'justify-content': 'center',
        display: 'flex',
        padding: '0 .5em',
        'font-size': '16px',
        'text-decoration': 'none',
        color: 'white',
      },
      hover: {
        'background-color': '#2762E8',
      },
      dropdown: {
        item: {
          display: 'flex',
          position: 'relative',
        },
        icon: {
          'margin-left': ' 0.5rem',
          'font-weight': 'bold',
          transition: 'transform 300ms',
        },
        content: {
          display: 'none',
          'flex-direction': 'column',
          position: 'absolute',
          left: 0,
          top: '10vh',
          width: '100%',
          padding: 0,
          height: 'max-content',
          'background-color': '#2B34FF',
          animation: 'slide 300ms ease',
        },
      },
      keyframes: {
        name: 'silde',
        from: {
          opacity: 0,
          transform: 'translateY(-60px)',
        },
        to: {
          opacity: 1,
          transform: 'translateY(0)',
        },
      },
    },
    items: ['Home', 'Contacts', 'About'],
    dropdown: {
      title: 'Dropdown',
      items: ['Media', 'Downloads'],
    },
  }),
  new Section({
    id: 'nav-14',
    title: 'Dropdown Red',
    type: 'dropdown',
    styles: {
      nav: {
        display: 'flex',
        'justify-content': 'space-between',
        'align-items': 'center',
        color: 'white',
        'background-color': '#CC000E',
        height: '10vh',
        margin: '1em 0',
      },
      logo: {
        'font-size': '24px',
        'letter-spacing': '2px',
        'padding-left': '1.5em',
      },
      list: {
        display: 'flex',
        'justify-content': 'space-around',
        padding: '0 1em',
        height: '100%',
      },
      item: {
        display: 'flex',
        transition: 'background-color 200ms',
        'align-items': 'center',
        padding: '0 1.5rem',
      },
      link: {
        'flex-direction': 'column',
        'align-items': 'center',
        'justify-content': 'center',
        display: 'flex',
        padding: '0 .5em',
        'font-size': '16px',
        'text-decoration': 'none',
        color: 'white',
      },
      hover: {
        'background-color': '#FF5719',
      },
      dropdown: {
        item: {
          display: 'flex',
          position: 'relative',
        },
        icon: {
          'margin-left': ' 0.5rem',
          'font-weight': 'bold',
          transition: 'transform 300ms',
        },
        content: {
          display: 'none',
          'flex-direction': 'column',
          position: 'absolute',
          left: 0,
          top: '10vh',
          width: '100%',
          padding: 0,
          height: 'max-content',
          'background-color': '#CC000E',
          animation: 'slide 300ms ease',
        },
      },
      keyframes: {
        name: 'silde',
        from: {
          opacity: 0,
          transform: 'translateY(-60px)',
        },
        to: {
          opacity: 1,
          transform: 'translateY(0)',
        },
      },
    },
    items: ['Home', 'Contacts', 'About'],
    dropdown: {
      title: 'Dropdown',
      items: ['Media', 'Downloads'],
    },
  }),
  new Section({
    id: 'nav-15',
    title: 'Dropdown Green',
    type: 'dropdown',
    styles: {
      nav: {
        display: 'flex',
        'justify-content': 'space-between',
        'align-items': 'center',
        color: 'white',
        'background-color': '#00800B',
        height: '10vh',
        margin: '1em 0',
      },
      logo: {
        'font-size': '24px',
        'letter-spacing': '2px',
        'padding-left': '1.5em',
      },
      list: {
        display: 'flex',
        'justify-content': 'space-around',
        padding: '0 1em',
        height: '100%',
      },
      item: {
        display: 'flex',
        transition: 'background-color 200ms',
        'align-items': 'center',
        padding: '0 1.5rem',
      },
      link: {
        'flex-direction': 'column',
        'align-items': 'center',
        'justify-content': 'center',
        display: 'flex',
        padding: '0 .5em',
        'font-size': '16px',
        'text-decoration': 'none',
        color: 'white',
      },
      hover: {
        'background-color': '#00990D',
      },
      dropdown: {
        item: {
          display: 'flex',
          position: 'relative',
        },
        icon: {
          'margin-left': ' 0.5rem',
          'font-weight': 'bold',
          transition: 'transform 300ms',
        },
        content: {
          display: 'none',
          'flex-direction': 'column',
          position: 'absolute',
          left: 0,
          top: '10vh',
          width: '100%',
          padding: 0,
          height: 'max-content',
          'background-color': '#00800B',
          animation: 'slide 300ms ease',
        },
      },
      keyframes: {
        name: 'silde',
        from: {
          opacity: 0,
          transform: 'translateY(-60px)',
        },
        to: {
          opacity: 1,
          transform: 'translateY(0)',
        },
      },
    },
    items: ['Home', 'Contacts', 'About'],
    dropdown: {
      title: 'Dropdown',
      items: ['Media', 'Downloads'],
    },
  }),
  new Section({
    id: 'nav-16',
    title: 'Dropdown Orange',
    type: 'dropdown',
    styles: {
      nav: {
        display: 'flex',
        'justify-content': 'space-between',
        'align-items': 'center',
        color: 'white',
        'background-color': '#E3780E',
        height: '10vh',
        margin: '1em 0',
      },
      logo: {
        'font-size': '24px',
        'letter-spacing': '2px',
        'padding-left': '1.5em',
      },
      list: {
        display: 'flex',
        'justify-content': 'space-around',
        padding: '0 1em',
        height: '100%',
      },
      item: {
        display: 'flex',
        transition: 'background-color 200ms',
        'align-items': 'center',
        padding: '0 1.5rem',
      },
      link: {
        'flex-direction': 'column',
        'align-items': 'center',
        'justify-content': 'center',
        display: 'flex',
        padding: '0 .5em',
        'font-size': '16px',
        'text-decoration': 'none',
        color: 'white',
      },
      hover: {
        'background-color': '#E89E53',
      },
      dropdown: {
        item: {
          display: 'flex',
          position: 'relative',
        },
        icon: {
          'margin-left': ' 0.5rem',
          'font-weight': 'bold',
          transition: 'transform 300ms',
        },
        content: {
          display: 'none',
          'flex-direction': 'column',
          position: 'absolute',
          left: 0,
          top: '10vh',
          width: '100%',
          padding: 0,
          height: 'max-content',
          'background-color': '#E3780E',
          animation: 'slide 300ms ease',
        },
      },
      keyframes: {
        name: 'silde',
        from: {
          opacity: 0,
          transform: 'translateY(-60px)',
        },
        to: {
          opacity: 1,
          transform: 'translateY(0)',
        },
      },
    },
    items: ['Home', 'Contacts', 'About'],
    dropdown: {
      title: 'Dropdown',
      items: ['Media', 'Downloads'],
    },
  }),
  new Section({
    id: 'nav-17',
    title: 'Dropdown Purple',
    type: 'dropdown',
    styles: {
      nav: {
        display: 'flex',
        'justify-content': 'space-between',
        'align-items': 'center',
        color: 'white',
        'background-color': '#520763',
        height: '10vh',
        margin: '1em 0',
      },
      logo: {
        'font-size': '24px',
        'letter-spacing': '2px',
        'padding-left': '1.5em',
      },
      list: {
        display: 'flex',
        'justify-content': 'space-around',
        padding: '0 1em',
        height: '100%',
      },
      item: {
        display: 'flex',
        transition: 'background-color 200ms',
        'align-items': 'center',
        padding: '0 1.5rem',
      },
      link: {
        'flex-direction': 'column',
        'align-items': 'center',
        'justify-content': 'center',
        display: 'flex',
        padding: '0 .5em',
        'font-size': '16px',
        'text-decoration': 'none',
        color: 'white',
      },
      hover: {
        'background-color': '#9C41B0',
      },
      dropdown: {
        item: {
          display: 'flex',
          position: 'relative',
        },
        icon: {
          'margin-left': ' 0.5rem',
          'font-weight': 'bold',
          transition: 'transform 300ms',
        },
        content: {
          display: 'none',
          'flex-direction': 'column',
          position: 'absolute',
          left: 0,
          top: '10vh',
          width: '100%',
          padding: 0,
          height: 'max-content',
          'background-color': '#520763',
          animation: 'slide 300ms ease',
        },
      },
      keyframes: {
        name: 'silde',
        from: {
          opacity: 0,
          transform: 'translateY(-60px)',
        },
        to: {
          opacity: 1,
          transform: 'translateY(0)',
        },
      },
    },
    items: ['Home', 'Contacts', 'About'],
    dropdown: {
      title: 'Dropdown',
      items: ['Media', 'Downloads'],
    },
  }),
  new Section({
    id: 'nav-18',
    title: 'Dropdown Aqua',
    type: 'dropdown',
    styles: {
      nav: {
        display: 'flex',
        'justify-content': 'space-between',
        'align-items': 'center',
        color: 'white',
        'background-color': '#3289A1',
        height: '10vh',
        margin: '1em 0',
      },
      logo: {
        'font-size': '24px',
        'letter-spacing': '2px',
        'padding-left': '1.5em',
      },
      list: {
        display: 'flex',
        'justify-content': 'space-around',
        padding: '0 1em',
        height: '100%',
      },
      item: {
        display: 'flex',
        transition: 'background-color 200ms',
        'align-items': 'center',
        padding: '0 1.5rem',
      },
      link: {
        'flex-direction': 'column',
        'align-items': 'center',
        'justify-content': 'center',
        display: 'flex',
        padding: '0 .5em',
        'font-size': '16px',
        'text-decoration': 'none',
        color: 'white',
      },
      hover: {
        'background-color': '#75AFBF',
      },
      dropdown: {
        item: {
          display: 'flex',
          position: 'relative',
        },
        icon: {
          'margin-left': ' 0.5rem',
          'font-weight': 'bold',
          transition: 'transform 300ms',
        },
        content: {
          display: 'none',
          'flex-direction': 'column',
          position: 'absolute',
          left: 0,
          top: '10vh',
          width: '100%',
          padding: 0,
          height: 'max-content',
          'background-color': '#3289A1',
          animation: 'slide 300ms ease',
        },
      },
      keyframes: {
        name: 'silde',
        from: {
          opacity: 0,
          transform: 'translateY(-60px)',
        },
        to: {
          opacity: 1,
          transform: 'translateY(0)',
        },
      },
    },
    items: ['Home', 'Contacts', 'About'],
    dropdown: {
      title: 'Dropdown',
      items: ['Media', 'Downloads'],
    },
  }),
  new Section({
    id: 'nav-19',
    title: 'Dropdown Wine',
    type: 'dropdown',
    styles: {
      nav: {
        display: 'flex',
        'justify-content': 'space-between',
        'align-items': 'center',
        color: 'white',
        'background-color': '#82100E',
        height: '10vh',
        margin: '1em 0',
      },
      logo: {
        'font-size': '24px',
        'letter-spacing': '2px',
        'padding-left': '1.5em',
      },
      list: {
        display: 'flex',
        'justify-content': 'space-around',
        padding: '0 1em',
        height: '100%',
      },
      item: {
        display: 'flex',
        transition: 'background-color 200ms',
        'align-items': 'center',
        padding: '0 1.5rem',
      },
      link: {
        'flex-direction': 'column',
        'align-items': 'center',
        'justify-content': 'center',
        display: 'flex',
        padding: '0 .5em',
        'font-size': '16px',
        'text-decoration': 'none',
        color: 'white',
      },
      hover: {
        'background-color': '#973F3E',
      },
      dropdown: {
        item: {
          display: 'flex',
          position: 'relative',
        },
        icon: {
          'margin-left': ' 0.5rem',
          'font-weight': 'bold',
          transition: 'transform 300ms',
        },
        content: {
          display: 'none',
          'flex-direction': 'column',
          position: 'absolute',
          left: 0,
          top: '10vh',
          width: '100%',
          padding: 0,
          height: 'max-content',
          'background-color': '#82100E',
          animation: 'slide 300ms ease',
        },
      },
      keyframes: {
        name: 'silde',
        from: {
          opacity: 0,
          transform: 'translateY(-60px)',
        },
        to: {
          opacity: 1,
          transform: 'translateY(0)',
        },
      },
    },
    items: ['Home', 'Contacts', 'About'],
    dropdown: {
      title: 'Dropdown',
      items: ['Media', 'Downloads'],
    },
  }),
  new Section({
    id: 'nav-110',
    title: 'Dropdown Slime',
    type: 'dropdown',
    styles: {
      nav: {
        display: 'flex',
        'justify-content': 'space-between',
        'align-items': 'center',
        color: 'white',
        'background-color': '#827219',
        height: '10vh',
        margin: '1em 0',
      },
      logo: {
        'font-size': '24px',
        'letter-spacing': '2px',
        'padding-left': '1.5em',
      },
      list: {
        display: 'flex',
        'justify-content': 'space-around',
        padding: '0 1em',
        height: '100%',
      },
      item: {
        display: 'flex',
        transition: 'background-color 200ms',
        'align-items': 'center',
        padding: '0 1.5rem',
      },
      link: {
        'flex-direction': 'column',
        'align-items': 'center',
        'justify-content': 'center',
        display: 'flex',
        padding: '0 .5em',
        'font-size': '16px',
        'text-decoration': 'none',
        color: 'white',
      },
      hover: {
        'background-color': '#978B4A',
      },
      dropdown: {
        item: {
          display: 'flex',
          position: 'relative',
        },
        icon: {
          'margin-left': ' 0.5rem',
          'font-weight': 'bold',
          transition: 'transform 300ms',
        },
        content: {
          display: 'none',
          'flex-direction': 'column',
          position: 'absolute',
          left: 0,
          top: '10vh',
          width: '100%',
          padding: 0,
          height: 'max-content',
          'background-color': '#827219',
          animation: 'slide 300ms ease',
        },
      },
      keyframes: {
        name: 'silde',
        from: {
          opacity: 0,
          transform: 'translateY(-60px)',
        },
        to: {
          opacity: 1,
          transform: 'translateY(0)',
        },
      },
    },
    items: ['Home', 'Contacts', 'About'],
    dropdown: {
      title: 'Dropdown',
      items: ['Media', 'Downloads'],
    },
  }),
];
