import { Section } from '../classes/section';

export const simple = [
  new Section({
    id: 'nav-1',
    title: 'Simple Dark',
    type: 'simple',
    styles: {
      nav: {
        display: 'flex',
        'justify-content': 'space-between',
        'align-items': 'center',
        color: 'white',
        'background-color': 'rgb(0, 0, 0)',
        height: '10vh',
        margin: '1em 0',
      },
      logo: {
        'font-size': '24px',
        'letter-spacing': '2px',
        'padding-left': '1.5em',
      },
      list: {
        display: 'flex',
        'justify-content': 'space-around',
        padding: '0 1em',
        height: '100%',
      },
      item: {
        display: 'flex',
        transition: 'background-color 200ms',
      },
      link: {
        'flex-direction': 'column',
        'align-items': 'center',
        'justify-content': 'center',
        display: 'flex',
        padding: '0 1.5em',
        'font-size': '16px',
        'text-decoration': 'none',
        color: 'white',
      },
      hover: {
        'background-color': 'gray',
      },
    },
    items: ['Home', 'Contacts', 'About'],
  }),
  new Section({
    id: 'nav-2',
    title: 'Simple Light',
    type: 'simple',
    styles: {
      nav: {
        display: 'flex',
        'justify-content': 'space-between',
        'align-items': 'center',
        color: 'black',
        'background-color': 'rgb(255,255,255)',
        height: '10vh',
        margin: '1em 0',
      },
      logo: {
        'font-size': '24px',
        'letter-spacing': '2px',
        'padding-left': '1.5em',
      },
      list: {
        display: 'flex',
        'justify-content': 'space-around',
        padding: '0 1em',
        height: '100%',
      },
      item: {
        display: 'flex',
        transition: 'background-color 200ms',
      },
      link: {
        'flex-direction': 'column',
        'align-items': 'center',
        'justify-content': 'center',
        display: 'flex',
        padding: '0 1.5em',
        'font-size': '16px',
        'text-decoration': 'none',
        color: 'black',
      },
      hover: {
        'background-color': 'lightgray',
      },
    },
    items: ['Home', 'Contacts', 'About'],
  }),
  new Section({
    id: 'nav-3',
    title: 'Simple Blue',
    type: 'simple',
    styles: {
      nav: {
        display: 'flex',
        'justify-content': 'space-between',
        'align-items': 'center',
        color: 'white',
        'background-color': '#2B34FF',
        height: '10vh',
        margin: '1em 0',
      },
      logo: {
        'font-size': '24px',
        'letter-spacing': '2px',
        'padding-left': '1.5em',
      },
      list: {
        display: 'flex',
        'justify-content': 'space-around',
        padding: '0 1em',
        height: '100%',
      },
      item: {
        display: 'flex',
        transition: 'background-color 200ms',
      },
      link: {
        'flex-direction': 'column',
        'align-items': 'center',
        'justify-content': 'center',
        display: 'flex',
        padding: '0 1.5em',
        'font-size': '16px',
        'text-decoration': 'none',
        color: 'white',
      },
      hover: {
        'background-color': '#2762E8',
      },
    },
    items: ['Home', 'Contacts', 'About'],
  }),
  new Section({
    id: 'nav-4',
    title: 'Simple Red',
    type: 'simple',
    styles: {
      nav: {
        display: 'flex',
        'justify-content': 'space-between',
        'align-items': 'center',
        color: 'white',
        'background-color': '#CC000E',
        height: '10vh',
        margin: '1em 0',
      },
      logo: {
        'font-size': '24px',
        'letter-spacing': '2px',
        'padding-left': '1.5em',
      },
      list: {
        display: 'flex',
        'justify-content': 'space-around',
        padding: '0 1em',
        height: '100%',
      },
      item: {
        display: 'flex',
        transition: 'background-color 200ms',
      },
      link: {
        'flex-direction': 'column',
        'align-items': 'center',
        'justify-content': 'center',
        display: 'flex',
        padding: '0 1.5em',
        'font-size': '16px',
        'text-decoration': 'none',
        color: 'white',
      },
      hover: {
        'background-color': '#FF5719',
      },
    },
    items: ['Home', 'Contacts', 'About'],
  }),
  new Section({
    id: 'nav-5',
    title: 'Simple Green',
    type: 'simple',
    styles: {
      nav: {
        display: 'flex',
        'justify-content': 'space-between',
        'align-items': 'center',
        color: 'white',
        'background-color': '#00800B',
        height: '10vh',
        margin: '1em 0',
      },
      logo: {
        'font-size': '24px',
        'letter-spacing': '2px',
        'padding-left': '1.5em',
      },
      list: {
        display: 'flex',
        'justify-content': 'space-around',
        padding: '0 1em',
        height: '100%',
      },
      item: {
        display: 'flex',
        transition: 'background-color 200ms',
      },
      link: {
        'flex-direction': 'column',
        'align-items': 'center',
        'justify-content': 'center',
        display: 'flex',
        padding: '0 1.5em',
        'font-size': '16px',
        'text-decoration': 'none',
        color: 'white',
      },
      hover: {
        'background-color': '#00990D',
      },
    },
    items: ['Home', 'Contacts', 'About'],
  }),
  new Section({
    id: 'nav-6',
    title: 'Simple Orange',
    type: 'simple',
    styles: {
      nav: {
        display: 'flex',
        'justify-content': 'space-between',
        'align-items': 'center',
        color: 'white',
        'background-color': '#E3780E',
        height: '10vh',
        margin: '1em 0',
      },
      logo: {
        'font-size': '24px',
        'letter-spacing': '2px',
        'padding-left': '1.5em',
      },
      list: {
        display: 'flex',
        'justify-content': 'space-around',
        padding: '0 1em',
        height: '100%',
      },
      item: {
        display: 'flex',
        transition: 'background-color 200ms',
      },
      link: {
        'flex-direction': 'column',
        'align-items': 'center',
        'justify-content': 'center',
        display: 'flex',
        padding: '0 1.5em',
        'font-size': '16px',
        'text-decoration': 'none',
        color: 'white',
      },
      hover: {
        'background-color': '#E89E53',
      },
    },
    items: ['Home', 'Contacts', 'About'],
  }),
  new Section({
    id: 'nav-7',
    title: 'Simple Purple',
    type: 'simple',
    styles: {
      nav: {
        display: 'flex',
        'justify-content': 'space-between',
        'align-items': 'center',
        color: 'white',
        'background-color': '#520763',
        height: '10vh',
        margin: '1em 0',
      },
      logo: {
        'font-size': '24px',
        'letter-spacing': '2px',
        'padding-left': '1.5em',
      },
      list: {
        display: 'flex',
        'justify-content': 'space-around',
        padding: '0 1em',
        height: '100%',
      },
      item: {
        display: 'flex',
        transition: 'background-color 200ms',
      },
      link: {
        'flex-direction': 'column',
        'align-items': 'center',
        'justify-content': 'center',
        display: 'flex',
        padding: '0 1.5em',
        'font-size': '16px',
        'text-decoration': 'none',
        color: 'white',
      },
      hover: {
        'background-color': '#9C41B0',
      },
    },
    items: ['Home', 'Contacts', 'About'],
  }),
  new Section({
    id: 'nav-8',
    title: 'Simple Aqua',
    type: 'simple',
    styles: {
      nav: {
        display: 'flex',
        'justify-content': 'space-between',
        'align-items': 'center',
        color: 'white',
        'background-color': '#3289A1',
        height: '10vh',
        margin: '1em 0',
      },
      logo: {
        'font-size': '24px',
        'letter-spacing': '2px',
        'padding-left': '1.5em',
      },
      list: {
        display: 'flex',
        'justify-content': 'space-around',
        padding: '0 1em',
        height: '100%',
      },
      item: {
        display: 'flex',
        transition: 'background-color 200ms',
      },
      link: {
        'flex-direction': 'column',
        'align-items': 'center',
        'justify-content': 'center',
        display: 'flex',
        padding: '0 1.5em',
        'font-size': '16px',
        'text-decoration': 'none',
        color: 'white',
      },
      hover: {
        'background-color': '#75AFBF',
      },
    },
    items: ['Home', 'Contacts', 'About'],
  }),
  new Section({
    id: 'nav-9',
    title: 'Simple Wine',
    type: 'simple',
    styles: {
      nav: {
        display: 'flex',
        'justify-content': 'space-between',
        'align-items': 'center',
        color: 'white',
        'background-color': '#82100E',
        height: '10vh',
        margin: '1em 0',
      },
      logo: {
        'font-size': '24px',
        'letter-spacing': '2px',
        'padding-left': '1.5em',
      },
      list: {
        display: 'flex',
        'justify-content': 'space-around',
        padding: '0 1em',
        height: '100%',
      },
      item: {
        display: 'flex',
        transition: 'background-color 200ms',
      },
      link: {
        'flex-direction': 'column',
        'align-items': 'center',
        'justify-content': 'center',
        display: 'flex',
        padding: '0 1.5em',
        'font-size': '16px',
        'text-decoration': 'none',
        color: 'white',
      },
      hover: {
        'background-color': '#973F3E',
      },
    },
    items: ['Home', 'Contacts', 'About'],
  }),
  new Section({
    id: 'nav-10',
    title: 'Simple Slime',
    type: 'simple',
    styles: {
      nav: {
        display: 'flex',
        'justify-content': 'space-between',
        'align-items': 'center',
        color: 'white',
        'background-color': '#827219',
        height: '10vh',
        margin: '1em 0',
      },
      logo: {
        'font-size': '24px',
        'letter-spacing': '2px',
        'padding-left': '1.5em',
      },
      list: {
        display: 'flex',
        'justify-content': 'space-around',
        padding: '0 1em',
        height: '100%',
      },
      item: {
        display: 'flex',
        transition: 'background-color 200ms',
      },
      link: {
        'flex-direction': 'column',
        'align-items': 'center',
        'justify-content': 'center',
        display: 'flex',
        padding: '0 1.5em',
        'font-size': '16px',
        'text-decoration': 'none',
        color: 'white',
      },
      hover: {
        'background-color': '#978B4A',
      },
    },
    items: ['Home', 'Contacts', 'About'],
  }),
];
